server:
  port: ${GATEWAY_SERVER_PORT}

spring:
  application:
    name: nikke-hub-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED}
      routes:
        - id: nikke-hub-backend
          uri: ${URI_BACKEND_SERVICE}
          predicates:
            - Path=/nikke/**

eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
  client:
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetchRegistry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}