apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:

  GATEWAY_SERVER_PORT: "8080"

  URI_BACKEND_SERVICE: lb://nikke-hub-backend-service

  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://nikke-hub-eureka-server-service:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"

  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"